micronaut:
  application:
    name: micronaut-testapp
r2dbc:
  datasources:
    default:
#      schema-generate: CREATE_DROP
      schema-generate: NONE
      dialect: POSTGRES
      db-type: postgres
      url: r2dbc:postgresql://localhost:5432/micronaut
      username: postgresadmin
      password: admin123

liquibase:
  datasources:
    default:
      change-log: "classpath:db/liquibase-changelog.xml"
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/micronaut
    username: postgresadmin
    password: admin123
    driverClassName: org.postgresql.Driver
    schema-generate: NONE
    dialect: POSTGRES
    db-type: postgres
